apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: rlmjob-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: rlm.io/v1alpha1
    resource: rlmjobs
  childResources:
    - apiVersion: v1
      resource: pods
      updateStrategy:
        method: Recreate
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://rlmjob-webhook.rlm-system.svc.cluster.local/sync
    finalize:
      webhook:
        url: http://rlmjob-webhook.rlm-system.svc.cluster.local/finalize
